### ISSUE TITLE
Network interfaces: eth0 vs eno1

### ISSUE THREAD

**Issue by jacksgt** [vision-it/vision-default#15]
On Debian 9 Stretch nodes, the `ipaddress_eth0` fact is not available, because the default network interface is `eno1` instead of `eth0`.

```
vision11 $ facter ipaddress_eth0

vision11 $ facter ipaddress_eno1
10.55.63.181
```

This leads to problems with `/etc/hosts` configs and exporting the correct ip address to PuppetDB

https://github.com/vision-it/vision-default/blob/dec61e0a85f25299f0ee53a0492514d1bbad2c84/manifests/init.pp#L30

**Comment by jacksgt** [comment]
What about using the (more generic) `ipaddress` fact?
```
vision11.prd (int) :: ~ : facter ipaddress
10.55.63.181
vision01.prd (int) :: ~ : facter ipaddress
10.55.63.153
```

**Comment by martialblog** [comment]
Sounds good
