### ISSUE TITLE
Move xrandr into own repository

### ISSUE THREAD

**Issue by martialblog** [vision-it/vision-default#6]
Since this file changes a lot, it might be smart to move it to its own repo
https://github.com/vision-it/vision-default/blob/production/files/xrandr.sh

**Comment by darkstar42** [comment]
We could also manage the display configuration via hiera.. ;)

**Comment by martialblog** [comment]
Done https://github.com/vision-it/vision-default/commit/94de70f0e78e98058ca42cc1ac57f56bab3df70f

Merged :shipit:
